/// <reference types="astro/client" />
/// <reference types="video.js" />

// worker-configuration.d.ts (generated by `wrangler types`) lives at the
// package root and is auto-included by tsconfig — it declares the
// `cloudflare:workers` module and the Env binding types.

declare module "@brightcove/player-loader";
